### PR TITLE
Remove UTF-8 quotation marks from AliasOrder test name

### PR DESCRIPTION
**Pull request by remiprev**
This should fix the OTP 18 and 19 compilation errors I introduced with #562 😬

### CODE REVIEW

**Comment by rrrene** [comment]
I wonder if this would classify as a bug in ExUnit ...

Thx! :+1:
